[project]
name = "swift-bus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "garden>=1.0.0b1",
    "kivy>=2.3.1",
    "kivy-garden>=0.1.5",
    "mapview>=1.0.6",
]
